on:
  webhook:
    method: post
jobs:
    action:
        name: 'Perform REST API'
        runs-on: ubuntu-latest
        steps:
            - name: 'get associated credentials'
              uses: actionsflow/axios@v1
              id: credentials
              with:
                url: 'https://api.hubapi.com/crm/v3/objects/contacts/${{ on.webhook.outputs.body.vid }}/associations/credential?limit=500'
                method: 'GET'
                bearer-token: ${{ secrets.HUBAPI }}
            - run: echo ${{ steps.credentials.outputs.status }}
            - run: echo ${{ steps.credentials.outputs.data }}
            - run: echo ${{ steps.credentials.outputs.headers }}
            - name: 'get associated tutor profile'
              uses: actionsflow/axios@v1
              id: tutorprofile
              with:
                url: 'https://api.hubapi.com/crm/v3/objects/contacts/${{ on.webhook.outputs.body.vid }}/associations/tutorprofile?limit=500'
                method: 'GET'
                bearer-token: ${{ secrets.HUBAPI }}
            - uses: actions/github-script@v5
              id: format
              with:
                script: |
                  var result = ${{ toJson(steps.credentials.outputs.data) }}
                  var credentialArray = []

                  result.forEach(function(e){
                    credentialArray.push({
                      "id": ""+e.id+""
                    })
                  })
                  return credentialArray;
            - name: 'get credentials details'
              uses: actionsflow/axios@v1
              id: credentialdetails
              with:
                url: 'https://api.hubapi.com/crm/v3/objects/credential/batch/read'
                method: 'POST'
                bearer-token: ${{ secrets.HUBAPI }}
                data: '{ "properties": [ "credential_type", "school_name" ], "inputs": ${{ steps.format.outputs.result }} }'
            - uses: actions/github-script@v5
              id: array
              with:
                script: |
                  var array = ${{ toJson(steps.credentialdetails.outputs.data) }}
                  var credentialDetailArray = []
                  array.forEach(function(e){
                    credentialDetailArray.push(e)
                  })
                  return JSON.stringify(credentialDetailArray);
            - name: 'update profile'
              uses: actionsflow/axios@v1
              id: updateprofile
              with:
                url: 'https://api.hubapi.com/crm/v3/objects/tutorprofile/${{ steps.tutorprofile.outputs.data[0].id }}'
                method: 'PATCH'
                bearer-token: ${{ secrets.HUBAPI }}
                data: '{ "properties": { "credential_array": "${{ steps.array.outputs.result }}" } }'
